### PR TITLE
Add deprecation notice

### PR DESCRIPTION
**Pull request by tianon**
cc @ehazlett @nathanleclaire @jeffdm @mchiang0610

Not ready for merge just yet, but should be prepped for the 1.8.0 release.

### CODE REVIEW

**Comment by tianon** [comment]
See also https://github.com/boot2docker/boot2docker/pull/1013.

**Comment by nathanleclaire** [comment]
LGTM

**Comment by nathanleclaire** [comment]
@moxiegirl Will https://docs.docker.com/installation/mac/ and https://docs.docker.com/installation/windows be re-written to reference the Toolbox instead?

**Comment by moxiegirl** [comment]
@nathanleclaire that's already done.  https://github.com/docker/docker/pull/14565

**Comment by ehazlett** [comment]
LGTM

**Comment by SvenDowideit** [comment]
LGTM, though I'd prefer to also have a proposed EOL date

**Comment by moxiegirl** [comment]
@SvenDowideit We can put an EOL notice on the Boot2Docker repo.

**Pull request merged**
