### PR TITLE
Bump installer to 1.6.0

### PR DESCRIPTION
**Pull request by ahmetalpbalkan**
:heart:

@tianon @SvenDowideit @icecrime

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
tianon pushed 8b508882bf06c19e70d02a63e773a4b1d09fdbc5. closing.

**Comment by tianon** [comment]
PATIENCE :bow:

**Comment by tianon** [comment]
:heart:

**Comment by ahmetalpbalkan** [comment]
will leave  this here as well just in case as a historical note

**Pull request closed without merging**
